name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      env:
        Configuration: Release
    - name: Compress build output
      run: Compress-Archive -Path $env:GITHUB_WORKSPACE\Filewatcher\bin\Release\net5.0-windows\* -DestinationPath $env:RUNNER_TEMP\build.zip
      shell: powershell
      env:
        RUNNER_TEMP: ${{ runner.temp }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
    - name: Publish binaries
      run: gh release upload 'v1.0' "${{ env.RUNNER_TEMP }}\\build.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUNNER_TEMP: ${{ runner.temp }}
    - name: Compress build output local
      run: Compress-Archive -Path $env:GITHUB_WORKSPACE\FilewatcherLocal\bin\Release\net5.0-windows\* -DestinationPath $env:RUNNER_TEMP\build-local.zip
      shell: powershell
      env:
        RUNNER_TEMP: ${{ runner.temp }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
    - name: Publish binaries
      run: gh release upload 'v1.0' "${{ env.RUNNER_TEMP }}\\build-local.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUNNER_TEMP: ${{ runner.temp }}

