name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      env:
            Configuration: Release
    - name: Archive Action
      # You may pin to the exact commit or the version.
      # uses: ihiroky/archive-action@e8b4644f992de8f7423e0bd7292c2e047ecf26ce
      uses: ihiroky/archive-action@v1
      with:
        # Root directory.
        root_dir: /bin/Release/net5.0/
        # Base directory; common prefix of all files and directories in the archive, relative to root_dir.
        # base_dir: # optional, default is .
        # Output file path. Supported extensions: zip, tar, tar.gz(tgz), tar.bz2(tbz2), tar.xz(txz)
        # file_path: # optional, default is output.zip
        # Shows details about the result of running this action.
        # verbose: # optional
    - name: Action Release
      # You may pin to the exact commit or the version.
      # uses: yakuhzi/release-asset@f96c41c3fdc53a02ab20a60014725490f91702a3
      uses: yakuhzi/release-asset@v1.2.3
      with:
        # File to upload to the release
        file: output.zip
        # Path to changelog file
        # changelog: # optional
